# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-19 14:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Todo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=200)),
                ('detail', models.CharField(max_length=500)),
                ('status', models.CharField(choices=[('P', 'Pending'), ('D', 'Done')], max_length=1)),
            ],
        ),
    ]
