# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-19 15:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='detail',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
        migrations.AlterField(
            model_name='todo',
            name='status',
            field=models.CharField(choices=[('P', 'Pending'), ('D', 'Done')], default='P', max_length=1),
        ),
    ]
